[package]
name = "ls-interactive"
description = "Interactive ls command"
authors = ["Araxeus <oaeben@gmail.com>"]
version = "1.0.3"
license = "MIT"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/Araxeus/ls-interactive"
repository = "https://github.com/you/ls-interactive"
keywords = ["ls", "lsi", "cli", "interactive", "explorer", "list", "files", "folders", "directory"]
categories = ["command-line-utilities"]

[dependencies]
dialoguer = "0.10.0"
console = "0.15.0"
opener = "0.5.0"

[[bin]]
name = "lsi"
path = "src/main.rs"
