name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    name: release ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - os: macos-latest
            filename: macos
          - os: ubuntu-latest
            filename: linux
          - os: windows-latest
            filename: windows 

    env:
      FILENAME: lsi_${{ matrix.filename }}_${{GITHUB_REF#refs/tags/}}.zip
    
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}

      - name: Build
        run: cargo build --release --verbose

      - name: Zip Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: Compress-Archive "target/release/lsi.exe" $Env:FILENAME -Force

      - name: Zip Linux / MacOs
        if: matrix.os != 'windows-latest'
        shell: sh
        run: zip -r -FS $FILENAME "target/release/lsi"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: $FILENAME
