name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    name: release ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - os: macos-latest
            filename: macos
          - os: ubuntu-latest
            filename: linux
          - os: windows-latest
            filename: windows

    steps:
      - name: Get the version
        id: version
        shell: sh
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get filename (Linux | MacOS)
        if: matrix.os != 'windows-latest'
        id: filename
        shell: sh
        run: echo ::set-output name=FILENAME::"lsi_${{ steps.version.outputs.VERSION }}_${{ matrix.filename }}.tar.gz"

      - name: Get filename (Windows)
        if: matrix.os == 'windows-latest'
        id: filename
        shell: sh
        run: echo ::set-output name=FILENAME::"lsi.exe"
    
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}

      - name: Build
        run: cargo build --release --verbose

      - name: Tar
        if: matrix.os != 'windows-latest'
        shell: sh
        run: tar cvzf ${{ steps.filename.outputs.FILENAME }} "target/release/lsi"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.FILENAME }}
