name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full


jobs:
  release:
    name: release ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/lsi.*
