name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    name: release ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - os: macos-latest
            filename: macos
          - os: ubuntu-latest
            filename: linux
          - os: windows-latest
            filename: windows 
    
    steps:
      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get filename
        id: filename
        run: echo ::set-output name=FILENAME::"lsi_${{ matrix.filename }}_${{ steps.version.outputs.VERSION }}.zip"

      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}

      - name: Build
        run: cargo build --release --verbose

      - name: Zip Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: "Compress-Archive target/release/lsi.exe ${{ steps.filename.outputs.FILENAME }} -Force"

      - name: Zip Linux / MacOs
        if: matrix.os != 'windows-latest'
        shell: sh
        run: zip -r -FS ${{ steps.filename.outputs.FILENAME }} "target/release/lsi"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.FILENAME }}
